version: "3.8"
services: 
  mevn-app:
    build: .
    ports: 
      - "5000:5000"
    environment: 
      - PORT=5000
      - NODE_ENV=production
    volumes: 
      - ~/images:/app/uploads

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - mongo-db:/data/db

volumes: 
  mongo-db:
